# Generated by Django 5.0.8 on 2024-08-29 08:27

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок Для отображения на сайте редактируется 1 пост')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью поста')),
            ],
            options={
                'verbose_name': 'Страница о сайте',
                'verbose_name_plural': 'Страница о сайте',
                'db_table': 'system_about',
            },
        ),
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью поста')),
            ],
            options={
                'verbose_name': 'Политика конфедициальности',
                'verbose_name_plural': 'Политика конфедициальности',
                'db_table': 'system_confederacy',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос ')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Ответ')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью поста')),
            ],
            options={
                'verbose_name': 'Часто задаваемые вопросы',
                'verbose_name_plural': 'Часто задаваемые вопросы',
                'db_table': 'system_faq',
            },
        ),
        migrations.CreateModel(
            name='Reklama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('urls', models.URLField(blank=True, max_length=255, verbose_name='URL')),
                ('text_url', models.CharField(blank=True, max_length=255, verbose_name='Текст url')),
                ('description', models.TextField(verbose_name='Описание')),
                ('thumbnail', models.ImageField(upload_to='images/reklama/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение')),
                ('status', models.CharField(choices=[('inwork', 'В работе'), ('stopped', 'Остановлена')], default='inwork', max_length=20, verbose_name='Статус рекламы')),
                ('placement', models.CharField(choices=[('header_banners_blog', 'Баннер в шапке раздела блог'), ('header_banners_news', 'Баннер в шапке раздела новости'), ('header_banners_all', 'Баннер в шапке сквозной'), ('left_blog', 'Баннер в левом блоке раздела блог'), ('left_news', 'Баннер в левом блоке раздела новости'), ('left_all', 'Баннер в левом блоке сквозной'), ('left_down_blog', 'Баннер снизу в левом блоке раздела блог'), ('left_down_news', 'Баннер снизу в левом блоке раздела новости'), ('left_down_all', 'Баннер снизу в левом блоке сквозной'), ('footer_banners_blog', 'Баннер в низу раздела блог'), ('footer_banners_news', 'Баннер в низу раздела новости'), ('footer_banners_all', 'Баннер в низу сквозной')], default='', max_length=20, verbose_name='Размещение рекламы')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('stop_time', models.DateTimeField(verbose_name='Время время окончания')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_reklama', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Реклама',
                'db_table': 'app_reklama',
                'ordering': ['-status', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес')),
                ('viewed_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата просмотра')),
                ('reklama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='system.reklama')),
            ],
            options={
                'verbose_name': 'Просмотр',
                'verbose_name_plural': 'Просмотры',
                'ordering': ('-viewed_on',),
            },
        ),
        migrations.AddIndex(
            model_name='reklama',
            index=models.Index(fields=['title', '-start_time', '-stop_time', 'status'], name='app_reklama_title_5db89d_idx'),
        ),
        migrations.AddIndex(
            model_name='viewcount',
            index=models.Index(fields=['-viewed_on'], name='system_view_viewed__5e733c_idx'),
        ),
    ]
