# Generated by Django 5.0.8 on 2024-08-23 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_reklama_viewcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='thumbnail',
            field=models.ImageField(upload_to='images/reklama/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Рекламный текст'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='urls',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
