# Generated by Django 5.0.8 on 2024-08-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_about_conf_faq_reklama_viewcount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='conf',
            table='system_conf',
        ),
    ]
