# Generated by Django 5.0.8 on 2024-08-26 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_reklama_thumbnail_alter_reklama_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='placement',
            field=models.CharField(choices=[('header_banners_blog', 'Баннер в шапке раздела блог'), ('header_banners_news', 'Баннер в шапке раздела новости'), ('header_banners_all', 'Баннер в шапке сквозной'), ('left_blog', 'Баннер в левом блоке раздела блог'), ('left_news', 'Баннер в левом блоке раздела новости'), ('left_all', 'Баннер в левом блоке сквозной'), ('left_down_blog', 'Баннер снизу в левом блоке раздела блог'), ('left_down_news', 'Баннер снизу в левом блоке раздела новости'), ('left_down_all', 'Баннер снизу в левом блоке сквозной'), ('footer_banners_blog', 'Баннер в низу раздела блог'), ('footer_banners_news', 'Баннер в низу раздела новости'), ('footer_banners_all', 'Баннер в низу сквозной')], default='', max_length=20, verbose_name='Размещение рекламы'),
        ),
        migrations.AlterField(
            model_name='reklama',
            name='thumbnail',
            field=models.ImageField(upload_to='images/reklama/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Изображение'),
        ),
    ]
