# Generated by Django 5.0.8 on 2024-08-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_conf_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
