# Generated by Django 5.0.8 on 2024-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_reklama_placement_alter_reklama_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reklama',
            name='text_url',
            field=models.CharField(blank=True, max_length=255, verbose_name='Текст url'),
        ),
    ]
