# Generated by Django 5.0.8 on 2024-08-29 09:08

import django.core.validators
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_conf_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок ')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
                ('thumbnail', models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью поста')),
            ],
            options={
                'verbose_name': 'Правила',
                'verbose_name_plural': 'Правила',
                'db_table': 'system_rules',
            },
        ),
    ]
