# Generated by Django 5.0.8 on 2024-08-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_reklamainfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reklama',
            name='placement',
            field=models.CharField(choices=[('header_banners_blog', 'Баннер в шапке сайта'), ('left_blog', 'Баннер в левом блоке'), ('left_down_blog', 'Баннер в левом блоке снизу'), ('footer_banners_blog', 'Баннер в подвале сайта')], default='', max_length=20, verbose_name='Размещение рекламы'),
        ),
    ]
