# Generated by Django 5.0.8 on 2024-08-28 19:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_faq_alter_about_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confederacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Политика конфедициальности',
                'verbose_name_plural': 'Политика конфедициальности',
                'db_table': 'system_confederacy',
            },
        ),
    ]
