# Generated by Django 5.0.8 on 2024-08-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_confederacy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confederacy',
            new_name='Conf',
        ),
    ]
