# Generated by Django 5.0.8 on 2024-08-28 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_rename_confederacy_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='images/thumbnails/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='превью поста'),
        ),
    ]
