# Generated by Django 5.0.8 on 2024-08-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_conf_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='thumbnail',
        ),
    ]
