# Generated by Django 5.0.8 on 2024-08-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree_conf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='agree_rules',
            field=models.BooleanField(default=False),
        ),
    ]
