# Generated by Django 5.0.8 on 2024-08-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_agree_conf_profile_agree_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='url_facebook',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_google',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на Google plus'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_instagram',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_pinterest',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на Pinterest'),
        ),
        migrations.AddField(
            model_name='profile',
            name='url_twitter',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка на Twitter'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agree_conf',
            field=models.BooleanField(default=False, verbose_name='Согласен с политикой конфедициальности'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agree_rules',
            field=models.BooleanField(default=False, verbose_name='Согласен с правилами сайта'),
        ),
    ]
