# Generated by Django 5.0.8 on 2024-09-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url_facebook',
            field=models.URLField(blank=True, help_text='Ссылка должна начинаться с: http:// или https://', max_length=255, verbose_name='Ссылка на Facebook'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_google',
            field=models.URLField(blank=True, help_text='Ссылка должна начинаться с: http:// или https://', max_length=255, verbose_name='Ссылка на Google plus'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_instagram',
            field=models.URLField(blank=True, help_text='Ссылка должна начинаться с: http:// или https://', max_length=255, verbose_name='Ссылка на Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_pinterest',
            field=models.URLField(blank=True, help_text='Ссылка должна начинаться с: http:// или https://', max_length=255, verbose_name='Ссылка на Pinterest'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='url_twitter',
            field=models.URLField(blank=True, help_text='Ссылка должна начинаться с: http:// или https://', max_length=255, verbose_name='Ссылка на Twitter'),
        ),
    ]
