# Generated by Django 5.0.7 on 2024-08-03 19:14

import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('parent', 'slug')},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=mptt.fields.TreeManyToManyField(related_name='articles', to='blog.category', verbose_name='Категории'),
        ),
    ]
